### ISSUE TITLE
chore: 회고 목록 조회 기능 수정

### ISSUE THREAD

**Issue by mikekks** [depromeet/layer-server#221]
### 마감
* 마감일 날짜 입력 하지 않은 경우
    * 자동 마감 : 모든 인원이 다 작성한 경우 
        * 마지막 인원이 다 작성한 시점이 마감된 시점에 마감된 회고로 들어간다. [RetroStatus.DONE]
    * 수동 마감 : 
        * 마감된 회고다. 마감일이 지정되지 않았기 때문에 [RetroStatus.DONE]
* 마감일 날짜 입력 한 경우
    * 자동 마감 : 
        * 마감 날짜가 지난 경우 마감된 회고로 들어간다. [RetroStatus.DONE]
    * 수동 마감 : 
        * 아직 진행중인 회고, 마감일이 지나면 마감된 회고로 들어간다.[ RetroStatus.DONE ]

### 분석
* 회고 목록 조회 API
* 회고 작성 API
* 회고 마감 API

### 분석이 들어가는 시점

* 수동마감 -> 무조건 아래로
* 모든 인원이 다 작성한 경우 
    * (마감 날짜가 있고, 모든 사람이 다 작성했는데 아직 마감 날짜가 안 지난 경우) -> "진행중" && "분석 완료" 가능
* 마감날짜가 지난 경우 -> 무조건 아래로

## ✅ Todo 

- [x] 회고 목록 조회 API 수정
- [x] 회고 작성 API 수정
- [x] 회고 마감 API 수정
- [x] 스케줄러 기능 수정
