### ISSUE TITLE
fix: 회고에서 탈퇴 멤버의 정보가 보이지 않음

### ISSUE THREAD

**Issue by clean2001** [depromeet/layer-server#222]
## 🚀 About Issue 🚀

탈퇴멤버의 회고답변이 이렇게 표시된다
<img width="469" alt="스크린샷 2024-09-11 오후 10 37 57" src="https://github.com/user-attachments/assets/578a5739-b3e9-41b3-8d71-8b70d16c4013">

다음 정책으로 구현 변경
- 탈퇴한 멤버의 회고 내용은 그대로 남겨둠 (이름, 회고 내용 모두)
- 회고 내용 화면 - 질문 탭 내 멤버 명 라벨링에 대해 해당 멤버 이름 회색으로 비활성화 느낌으로 처리
- 팀원 멤버 확인 화면 - 멤버 수와 리스트에선 제외 처리.

## ✅ Todo 

- [x] 멤버 soft delete로 변경
- [ ] 회고 결과에서 멤버가 탈퇴된 회원인지 표시
- [ ] 팀원 멤버 조회 API에서 탈퇴된 멤버는 제외
