### ISSUE TITLE
refactor: 코드 구조 개선

### ISSUE THREAD

**Issue by mikekks** [depromeet/layer-server#278]
## ✅ Todo 

- [x] depoly.sh 의 헬스 체크 방식 -> 액츄에이터 사용 
- [ ] dockerfile 범용성 높이기
- [x] 미사용 인프라 및 파일 정리
