### ISSUE TITLE
fix: 기본 템플릿 리뷰 사항 반영

### ISSUE THREAD

**Issue by clean2001** [depromeet/layer-server#83]
## 🚀 About Issue 🚀

#63에서 리뷰받았던 사항을 반영하려고 합니다.

## ✅ Todo 

- [ ] 리턴타입이 리스트인 경우 dto로 감싸는 것 (논의 필요)
- [x] 필요없는 log 코드 제거
- [x] TemplateService에서 전체 조회 시 enum 타입으로 불러오도록 수정
